### ISSUE TITLE
Upgrade to Laravel 10 fails

### ISSUE THREAD

**Issue by naimulkazma** [jeremykenedy/laravel-roles#195] opened 2023-02-15 14:32 UTC
composer require jeremykenedy/laravel-roles
Using version ^9.1 for jeremykenedy/laravel-roles
./composer.json has been updated
Running composer update jeremykenedy/laravel-roles
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support[v5.6.0, ..., v5.8.36] require php ^7.1.3 -> your php version (8.1.12) does not satisfy that requirement.
    - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.12) does not satisfy that requirement.
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.12) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.12) does not satisfy that requirement.
    - Root composer.json requires jeremykenedy/laravel-roles ^9.1 -> satisfiable by jeremykenedy/laravel-roles[v9.1.0].
    - eklundkristoffer/seedster 5.0 requires illuminate/support 5.5.*|5.6.*|5.7.*|5.8.*|6.*|^7.0|^8.0|^9.0 -> satisfiable by illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0].
    - Only one of these can be installed: illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - jeremykenedy/laravel-roles v9.1.0 requires eklundkristoffer/seedster ^5.0 -> satisfiable by eklundkristoffer/seedster[5.0].
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0].

**Comment by alkoumi** [comment] 2023-02-16 07:00
same thing here in new laravel 10

 composer require jeremykenedy/laravel-roles
./composer.json has been updated
Running composer update jeremykenedy/laravel-rolesase/      lang/          node_modules/  public/        resources/     routes/        storage/       tests/         vendor/      
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jeremykenedy/laravel-roles v9.1.0 requires eklundkristoffer/seedster ^5.0 -> satisfiable by eklundkristoffer/seedster[5.0].
    - jeremykenedy/laravel-roles[v1.0.0, ..., v1.0.1] require laravel/framework 5.4.* -> found laravel/framework[v5.4.0, ..., v5.4.36] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles v1.1.1 requires laravel/framework 5.3.*|5.4.*|5.5.* -> found laravel/framework[v5.3.0, ..., v5.5.50] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles v1.2.0 requires laravel/framework 5.3.*|5.4.*|5.5.*|5.6.* -> found laravel/framework[v5.3.0, ..., v5.6.40] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles v1.3.0 requires laravel/framework 5.3.*|5.4.*|5.5.*|5.6.*|5.7.* -> found laravel/framework[v5.3.0, ..., v5.7.29] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles[v1.4.0, ..., v1.7.0, v2.0.0, ..., v2.1.0] require laravel/framework 5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.* -> found laravel/framework[v5.3.0, ..., v5.8.38] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles[v2.2.0, ..., v2.3.1] require laravel/framework 5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|6.* -> found laravel/framework[v5.3.0, ..., v5.8.38, v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles[v2.3.3, ..., v2.9.0, v3.0.0, ..., v3.8.0, v4.0.0] require php ^7.2 -> your php version (8.1.14) does not satisfy that requirement.
    - jeremykenedy/laravel-roles[v5.0.0, ..., v5.1.0, v6.0.0, v7.0.0] require laravel/framework 5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|6.*|7.*|8.* -> found laravel/framework[v5.3.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).
    - jeremykenedy/laravel-roles[v8.0.0, ..., v8.1.0, v9.0.0] require laravel/framework 5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|6.*|7.*|8.*|^9.0 -> found laravel/framework[v5.3.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^10.0).
    - eklundkristoffer/seedster 5.0 requires illuminate/support 5.5.*|5.6.*|5.7.*|5.8.*|6.*|^7.0|^8.0|^9.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires jeremykenedy/laravel-roles * -> satisfiable by jeremykenedy/laravel-roles[v1.0.0, ..., v1.7.0, v2.0.0, ..., v2.9.0, v3.0.0, ..., v3.8.0, v4.0.0, v5.0.0, v5.1.0, v6.0.0, v7.0.0, v8.0.0, v8.1.0, v9.0.0, v9.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require jeremykenedy/laravel-roles:*" to figure out if any version is installable, or "composer require jeremykenedy/laravel-roles:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by jeremykenedy** [comment] 2023-02-16 12:53
Duplicate of 193

**Closed by jeremykenedy** 2023-02-16 12:53 UTC
